# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-15 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phoneinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobilename', models.CharField(max_length=64, verbose_name='\u624b\u673a\u540d\u79f0')),
                ('ios_or_andriod', models.CharField(max_length=10, verbose_name='\u624b\u673a\u7cfb\u7edf\u7c7b\u578b')),
                ('resolution_rate', models.CharField(max_length=20, verbose_name='\u624b\u673a\u5206\u8fa8\u7387')),
                ('system_name', models.CharField(max_length=20, verbose_name='\u7cfb\u7edf\u578b\u53f7')),
                ('is_comprehensive_screen', models.BooleanField(verbose_name='\u662f\u5426\u4e3a\u5168\u9762\u5c4f')),
                ('is_fingerprint', models.BooleanField(verbose_name='\u662f\u5426\u4e3a\u652f\u6301\u6307\u7eb9')),
                ('status', models.BooleanField(verbose_name='\u501f\u51fa\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u624b\u673a\u4fe1\u606f',
                'verbose_name_plural': '\u624b\u673a\u4fe1\u606f',
            },
        ),
    ]
