# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-30 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_record_info',
            name='yn',
            field=models.IntegerField(choices=[(0, '\u751f\u6548'), (1, '\u5931\u6548')], default=0),
        ),
    ]
