# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-15 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoneinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneinfo',
            old_name='mobilename',
            new_name='mobile_name',
        ),
    ]
