# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-30 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoneinfo', '0002_borrow_record_info_yn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow_record_info',
            name='yn',
        ),
    ]
