# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-15 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneinfo', '0002_auto_20181015_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneinfo',
            name='ios_or_andriod',
            field=models.IntegerField(choices=[(0, 'ios'), (1, 'andriod')], default=1),
        ),
    ]
