# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-16 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoneinfo', '0003_auto_20181015_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneinfo',
            old_name='ios_or_andriod',
            new_name='phone_type',
        ),
    ]
