# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-18 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoneinfo', '0006_phoneinfo_pic_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneinfo',
            old_name='is_fingerprint',
            new_name='is_finger_print',
        ),
    ]
