# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-18 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneinfo', '0007_auto_20181018_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneinfo',
            name='is_comprehensive_screen',
            field=models.IntegerField(choices=[(0, '\u5426'), (1, '\u662f')], default=0),
        ),
        migrations.AlterField(
            model_name='phoneinfo',
            name='is_finger_print',
            field=models.IntegerField(choices=[(0, '\u5426'), (1, '\u662f')], default=0),
        ),
    ]
