# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-23 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phoneinfo', '0009_auto_20181018_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow_record_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_person', models.CharField(max_length=20, verbose_name='\u501f\u51fa\u4eba')),
                ('borrow_department', models.CharField(max_length=20, null=True, verbose_name='\u501f\u51fa\u4eba\u90e8\u95e8')),
                ('borrow_time', models.DateTimeField(auto_now=True, verbose_name='\u501f\u51fa\u65f6\u95f4')),
                ('return_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5f52\u8fd8\u65f6\u95f4')),
                ('borrow_mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phoneinfo.Phoneinfo')),
            ],
            options={
                'verbose_name': '\u501f\u8fd8\u8bb0\u5f55',
                'verbose_name_plural': '\u501f\u8fd8\u8bb0\u5f55',
            },
        ),
    ]
