# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-23 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneinfo', '0011_phoneinfo_yn'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_record_info',
            name='yn',
            field=models.IntegerField(choices=[(0, '\u5df2\u5f52\u8fd8'), (1, '\u672a\u5f52\u8fd8')], default=1),
        ),
    ]
