# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-24 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneinfo', '0012_borrow_record_info_yn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow_record_info',
            old_name='yn',
            new_name='borrow_status',
        ),
        migrations.RemoveField(
            model_name='borrow_record_info',
            name='return_time',
        ),
        migrations.AddField(
            model_name='borrow_record_info',
            name='back_time',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='\u5f52\u8fd8\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='phoneinfo',
            name='yn',
            field=models.IntegerField(choices=[(0, '\u53ef\u7528'), (1, '\u4e0d\u53ef\u7528')], default=1),
        ),
    ]
