# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-25 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneinfo', '0014_auto_20181025_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneinfo',
            name='system_name',
            field=models.CharField(max_length=10, verbose_name='\u7cfb\u7edf\u578b\u53f7'),
        ),
    ]
