# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-25 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneinfo', '0015_auto_20181025_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_record_info',
            name='borrow_remark',
            field=models.CharField(max_length=100, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='phoneinfo',
            name='pic_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u56fe\u7247\u4e0a\u4f20\u8def\u5f84'),
        ),
    ]
