# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-25 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneinfo', '0016_auto_20181025_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_record_info',
            name='borrow_remark',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u5907\u6ce8'),
        ),
    ]
