# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-25 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneinfo', '0017_auto_20181025_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_record_info',
            name='borrow_remark',
            field=models.CharField(max_length=20, null=True, verbose_name='\u5907\u6ce8'),
        ),
    ]
